/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posprantik;

import posprantik.DAL.UserDAL;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class LoginJF extends javax.swing.JFrame {

    /**
     * Creates new form LoginJF
     */
    public LoginJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_UserName = new javax.swing.JTextField();
        txt_Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prantik POS - ||  LOG IN ");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogin.setText("LOG IN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("User Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Password");

        txt_UserName.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addComponent(txt_UserName)
                    .addComponent(txt_Password))
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_UserName, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(36, 36, 36)
                .addComponent(btnLogin)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
         try{
             ///
             
           //  String abc  = "http://192.168.5.21:9020/api/ELPLAPI/?_CODE=" + vCODE + '&_BID=' + vBID + '&_DEVICEID=' + vDEVICEID + '&_USER=' + vUSER + '&_DTime=' + vToday;
      //  String _UserName=txt_UserName.getText();
      //    String _Password=txt_Password.getText();
             
           // String abc    = "http://192.168.5.21:9020/api/ELPLAPI/?_UserName"+_UserName+"&_Password="+_Password;
             
             
             
             UserDAL app = new UserDAL();
app.CheckUser(txt_UserName.getText(), txt_Password.getText());

 // ResultSet rs  = pstmt.executeQuery();
 //JOptionPane.showMessageDialog(null, "Username and Password Matched");
            
//         HomeScreenJF HSJF= new HomeScreenJF();
//         HSJF.setExtendedState(Frame.MAXIMIZED_BOTH);
//         HSJF.setVisible(true);         
         this.setVisible(false);   
         this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
         this.dispose();
    
    
//    JFrame frame = new JFrame();
//frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
//frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//frame.setVisible(true);
    
    
             
//           // Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
//                       //jdbc:sqlserver://192.168.5.17:1555;databaseName=POSXCSEMI
//            String url="jdbc:sqlserver://192.168.5.17:1555;databaseName=POSXCSEMI;user=sa;password=sa9";
//            //String url="jdbc:sqlserver://192.168.5.17,1555;databaseName=testdb;user=sa;password=orchid";
//            Connection con = DriverManager.getConnection(url);
//            String sql = "Select * from EMPLOYEE_MASTER where EMP_ID=? and Salesforce_ID = ?";
//            PreparedStatement pst = con.prepareStatement(sql);
//            pst.setString(1, txt_UserName.getText());
//            pst.setString(2,txt_Password.getText());
//            
//             //SqlDataAdapter adpt = new SqlDataAdapter(cmd);
//           // adpt.Fill(dt);
//            ResultSet rs = pst.executeQuery();
//            if(rs.next()){
//                
//                 String EMP_ID = rs.getString("EMP_ID");
//                String Salesforce_ID = rs.getString("Salesforce_ID");
//              
//
//                System.out.printf("%s, %s", EMP_ID, Salesforce_ID);
//                JOptionPane.showMessageDialog(null, "Username and Password Matched");
//               // Succes field= new Succes();
//               // field.setVisible(true);
//              //  setVisible(false);
//              
//            HomeScreenJF jfrm2= new HomeScreenJF();
//            jfrm2.setSize(270, 160); 
//            jfrm2.setVisible(true);
//            this.setVisible(false);
//            this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
//     this.dispose();
//              
//            }
//            else{
//                JOptionPane.showMessageDialog(null, "Username and password not Correct");
//                txt_UserName.setText("");
//                txt_Password.setText("");
//            }
//          setText
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_UserName;
    // End of variables declaration//GEN-END:variables
}
